name: ising-solver
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip>=7.0
  - numpy>=1.11
  - scipy>=0.17
  - matplotlib>=1.5
  - pytest>=2.9
  - scikit-learn>=0.18
  - setuptools>=26
  - docutils>=0.3
  - tensorflow>=2.0.0
  - tqdm
  - pytorch
  - notebook
  - pip

# To fine tune the hyperparameters, we can use the following code
  - pip:
    - M-LOOP
    